### ISSUE TITLE
Missing link to 3D print file in mini-pan-tilt instructions

### ISSUE THREAD

**Issue by Seyij** [strawlab/flo-hardware#2]
Hello, thanks for the repo. In the instuctions here - https://github.com/strawlab/flo-hardware/blob/master/mini-pan-tilt/mini-pan-tilt-build-instructions.md at line 23. It doesn't include the link to the "custom 3D printed support bracket". It doesn't list the name of the file so I was unable to locate it.

**Comment by astraw** [comment]
Oh, we had forgotten to upload that particular file (and another one). We now updated the repo in 85364564bdc6918a3db84ef1b8dc5a44d9d6a73c and b97a988d5e35905346d01b98ac3c5f17215afbbb. Thanks for the note!
